[package]
name = "music_man"
version = "0.1.0"
authors = ["swpark6 <sewon1234@naver.com>", "supernovel <ekfueh@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack = "0.22.0"
